services:
  db:
    image: postgres:18-alpine
    container_name: stanthony
    ports:
      - '5434:5432'
    environment:
      POSTGRES_PASSWORD: stanthony
      POSTGRES_USER: stanthony
      POSTGRES_DB: stanthony
    volumes:
      - pgdata-stanthony:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - '1025:1025' # SMTP
      - '8025:8025' # Web UI

  cache:
    image: redis:8.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass stanthony

volumes:
  pgdata-stanthony:
  cache:
    driver: local
