services:
  db:
    image: postgres:18
    container_name: stanthony
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: stanthony
      POSTGRES_USER: stanthony
      POSTGRES_DB: stanthony
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - '1025:1025' # SMTP
      - '8025:8025' # Web UI

volumes:
  pgdata:
