module.exports = {
  apps: [
    {
      name: "St. Anthony",
      script: "dist/src/main.js",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      env: {
        NODE_ENV: "development",
        PORT: process.env.PORT || 3000,
        DATABASE_URL: process.env.DATABASE_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        MAIL_HOST: process.env.MAIL_HOST,
        MAIL_PORT: process.env.MAIL_PORT,
        MAIL_USER: process.env.MAIL_USER,
        MAIL_PASS: process.env.MAIL_PASS,
        MAIL_FROM: process.env.MAIL_FROM,
        JWT_PASSWORD_RESET_SECRET: process.env.JWT_PASSWORD_RESET_SECRET,
        JWT_PASSWORD_RESET_EXPIRATION_TIME: process.env.JWT_PASSWORD_RESET_EXPIRATION_TIME,
        JWT_USER_VERIFY_SECRET: process.env.JWT_USER_VERIFY_SECRET,
        JWT_USER_VERIFY_EXPIRATION_TIME: process.env.JWT_USER_VERIFY_EXPIRATION_TIME,
        FRONTEND_URL: process.env.FRONTEND_URL,
        EMAIL_RESET_PASSWORD_URL: process.env.EMAIL_RESET_PASSWORD_URL,
        USER_VERIFY_ACCOUNT_URL: process.env.USER_VERIFY_ACCOUNT_URL,
        REDIS_HOST: process.env.REDIS_HOST,
        REDIS_PORT: process.env.REDIS_PORT,
        REDIS_PASSWORD: process.env.REDIS_PASSWORD,
        IMAGES_PATH: process.env.IMAGES_PATH,
        STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
        CLOUDBEDS_ENABLED: process.env.CLOUDBEDS_ENABLED,
        CLOUDBEDS_CLIENT_ID: process.env.CLOUDBEDS_CLIENT_ID,
        CLOUDBEDS_CLIENT_SECRET: process.env.CLOUDBEDS_CLIENT_SECRET,
        CLOUDBEDS_WEBHOOK_SECRET: process.env.CLOUDBEDS_WEBHOOK_SECRET,
      },
      error_file: "logs/err.log",
      out_file: "logs/out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      time: true,
      min_uptime: "60s",
      max_restarts: 5,
      restart_delay: 3000,
      node_args: "--max-old-space-size=1024",
    },
  ],
};
