ALTER TABLE "amenities" ADD COLUMN "name_en" varchar(100);--> statement-breakpoint
ALTER TABLE "amenities" ADD COLUMN "name_fr" varchar(100);--> statement-breakpoint
ALTER TABLE "amenities" ADD COLUMN "name_de" varchar(100);--> statement-breakpoint
ALTER TABLE "highlights" ADD COLUMN "name_en" varchar(100);--> statement-breakpoint
ALTER TABLE "highlights" ADD COLUMN "name_fr" varchar(100);--> statement-breakpoint
ALTER TABLE "highlights" ADD COLUMN "name_de" varchar(100);--> statement-breakpoint
ALTER TABLE "room_types" ADD COLUMN "name_en" varchar(100);--> statement-breakpoint
ALTER TABLE "room_types" ADD COLUMN "name_fr" varchar(100);--> statement-breakpoint
ALTER TABLE "room_types" ADD COLUMN "name_de" varchar(100);--> statement-breakpoint
ALTER TABLE "properties" ADD COLUMN "name_en" varchar(255);--> statement-breakpoint
ALTER TABLE "properties" ADD COLUMN "name_fr" varchar(255);--> statement-breakpoint
ALTER TABLE "properties" ADD COLUMN "name_de" varchar(255);--> statement-breakpoint
ALTER TABLE "properties" ADD COLUMN "description_en" text;--> statement-breakpoint
ALTER TABLE "properties" ADD COLUMN "description_fr" text;--> statement-breakpoint
ALTER TABLE "properties" ADD COLUMN "description_de" text;--> statement-breakpoint
ALTER TABLE "properties" ADD COLUMN "about_en" text;--> statement-breakpoint
ALTER TABLE "properties" ADD COLUMN "about_fr" text;--> statement-breakpoint
ALTER TABLE "properties" ADD COLUMN "about_de" text;--> statement-breakpoint
ALTER TABLE "properties" ADD COLUMN "arrival_instructions_en" text;--> statement-breakpoint
ALTER TABLE "properties" ADD COLUMN "arrival_instructions_fr" text;--> statement-breakpoint
ALTER TABLE "properties" ADD COLUMN "arrival_instructions_de" text;--> statement-breakpoint
ALTER TABLE "rooms" ADD COLUMN "name_en" varchar(100);--> statement-breakpoint
ALTER TABLE "rooms" ADD COLUMN "name_fr" varchar(100);--> statement-breakpoint
ALTER TABLE "rooms" ADD COLUMN "name_de" varchar(100);--> statement-breakpoint
ALTER TABLE "rooms" ADD COLUMN "description_en" text;--> statement-breakpoint
ALTER TABLE "rooms" ADD COLUMN "description_fr" text;--> statement-breakpoint
ALTER TABLE "rooms" ADD COLUMN "description_de" text;--> statement-breakpoint
ALTER TABLE "residences" ADD COLUMN "name_en" varchar(255);--> statement-breakpoint
ALTER TABLE "residences" ADD COLUMN "name_fr" varchar(255);--> statement-breakpoint
ALTER TABLE "residences" ADD COLUMN "name_de" varchar(255);--> statement-breakpoint
ALTER TABLE "residences" ADD COLUMN "description_en" text;--> statement-breakpoint
ALTER TABLE "residences" ADD COLUMN "description_fr" text;--> statement-breakpoint
ALTER TABLE "residences" ADD COLUMN "description_de" text;--> statement-breakpoint
ALTER TABLE "residences" ADD COLUMN "about_en" text;--> statement-breakpoint
ALTER TABLE "residences" ADD COLUMN "about_fr" text;--> statement-breakpoint
ALTER TABLE "residences" ADD COLUMN "about_de" text;--> statement-breakpoint
ALTER TABLE "residence_units" ADD COLUMN "name_en" varchar(100);--> statement-breakpoint
ALTER TABLE "residence_units" ADD COLUMN "name_fr" varchar(100);--> statement-breakpoint
ALTER TABLE "residence_units" ADD COLUMN "name_de" varchar(100);--> statement-breakpoint
ALTER TABLE "residence_units" ADD COLUMN "description_en" text;--> statement-breakpoint
ALTER TABLE "residence_units" ADD COLUMN "description_fr" text;--> statement-breakpoint
ALTER TABLE "residence_units" ADD COLUMN "description_de" text;--> statement-breakpoint
ALTER TABLE "restaurants" ADD COLUMN "name_en" varchar(255);--> statement-breakpoint
ALTER TABLE "restaurants" ADD COLUMN "name_fr" varchar(255);--> statement-breakpoint
ALTER TABLE "restaurants" ADD COLUMN "name_de" varchar(255);--> statement-breakpoint
ALTER TABLE "restaurants" ADD COLUMN "description_en" text;--> statement-breakpoint
ALTER TABLE "restaurants" ADD COLUMN "description_fr" text;--> statement-breakpoint
ALTER TABLE "restaurants" ADD COLUMN "description_de" text;