import * as Joi from 'joi';
export const validationSchema = Joi.object({
  DATABASE_URL: Joi.string().uri().required(),
  JWT_SECRET: Joi.string().required(),
  MAIL_HOST: Joi.string().required(),
  MAIL_PORT: Joi.number().required(),
  MAIL_USER: Joi.string().required(),
  MAIL_PASS: Joi.string().required(),
  MAIL_FROM: Joi.string().required(),
  EMAIL_RESET_PASSWORD_URL: Joi.string().required(),
  USER_VERIFY_ACCOUNT_URL: Joi.string().required(),
  JWT_PASSWORD_RESET_SECRET: Joi.string().required(),
  JWT_PASSWORD_RESET_EXPIRATION_TIME: Joi.string().default('15m'),
  JWT_USER_VERIFY_SECRET: Joi.string().required(),
  JWT_USER_VERIFY_EXPIRATION_TIME: Joi.string().default('24h'),
  PAYPAL_CLIENT_ID: Joi.string().required(),
  PAYPAL_CLIENT_SECRET: Joi.string().required(),
  PAYPAL_MODE: Joi.string().default('sandbox'),
  FRONTEND_URL: Joi.string().default('http://localhost:4200'),
  REDIS_HOST: Joi.string().required(),
  REDIS_PORT: Joi.number().required(),
  REDIS_PASSWORD: Joi.string().required(),
  IMAGES_PATH: Joi.string().required(),
});
